# Generated by Django 2.0.2 on 2018-02-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='data_di_creazione',
            new_name='created_date',
        ),
    ]
