# Generated by Django 2.0.2 on 2018-02-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Gallery'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
