# Generated by Django 2.0.2 on 2018-02-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='descrizione_galleria',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='descrizione_photo',
        ),
    ]
