# Generated by Django 2.0.2 on 2018-02-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180213_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Upload',
            field=models.ImageField(default='', max_length=255, upload_to='static/'),
        ),
    ]
