# Generated by Django 2.0.2 on 2018-02-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_photo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Gallery',
            field=models.ManyToManyField(to='gallery.Gallery'),
        ),
    ]
