# Generated by Django 2.0.2 on 2018-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photo_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Gallery',
            field=models.ManyToManyField(blank=True, to='gallery.Gallery'),
        ),
    ]
