# Generated by Django 2.0.2 on 2018-02-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20180213_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Upload',
            new_name='Upload_photo',
        ),
        migrations.AddField(
            model_name='gallery',
            name='Gallery_Thumb',
            field=models.ImageField(default='', max_length=255, upload_to='static/'),
        ),
    ]
