# Generated by Django 2.0.2 on 2018-02-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20180213_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
