# Generated by Django 2.0.2 on 2018-02-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20180213_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Gallery',
            new_name='gallery',
        ),
    ]
