# Generated by Django 2.0.2 on 2018-02-14 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20180213_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cognome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Gallery_Thumb',
            field=models.ImageField(default='', max_length=255, upload_to='../static/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Upload_photo',
            field=models.ImageField(default='', max_length=255, upload_to='media/'),
        ),
    ]
