# Generated by Django 2.0.2 on 2018-02-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20180214_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
