# Generated by Django 2.0.2 on 2018-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Upload_photo',
            field=models.ImageField(default='', max_length=255, upload_to='static/'),
        ),
    ]
