# Generated by Django 2.0.2 on 2018-02-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_auto_20180215_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['my_order']},
        ),
    ]
