# Generated by Django 2.0.2 on 2018-02-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_auto_20180215_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['my_order_photo']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='my_order',
            new_name='my_order_photo',
        ),
    ]
