# Generated by Django 2.0.2 on 2018-02-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20180215_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='my_order_photo',
        ),
    ]
