# Generated by Django 2.0.2 on 2018-02-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_auto_20180215_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='gallery',
        ),
        migrations.AddField(
            model_name='photo',
            name='gallery',
            field=models.CharField(choices=[('residenziale', 'Residenziale'), ('hotel', 'Hotel'), ('interni', 'Interni'), ('ristrutturazione', 'Ristrutturazione'), ('villa', 'Villa'), ('commerciale', 'Commerciale')], default='residenziale', max_length=200),
        ),
    ]
