# Generated by Django 2.0.2 on 2018-02-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
